package com.browntowndev.liftlab.core.domain.enums

enum class TopAppBarAction {
    ReorderWorkouts,
    ReorderLifts,
    CreateNewWorkout,
    CreateNewProgram,
    ManagePrograms,
    RenameProgram,
    RenameWorkout,
    DeleteProgram,
    NavigatedBack,
    SearchTextChanged,
    FilterStarted,
    EditDeloadWeek,
    FinishWorkout,
    RestTimerCompleted,
    ConfirmAddLift,
    CreateNewLift,
    ConfirmCreateNewLift,
    OpenSettingsMenu,
    OpenWorkoutHistory,
    EditDateRange,
    OpenProfileMenu,
}