package com.browntowndev.liftlab.core.common


// Time
const val ONE_MINUTE_IN_MILLIS = 60000L
const val TEN_MINUTES_IN_MILLIS = 10 * ONE_MINUTE_IN_MILLIS
const val ONE_HOUR_IN_MILLIS = 60 * ONE_MINUTE_IN_MILLIS
const val TEN_HOURS_IN_MILLIS = 10 * ONE_HOUR_IN_MILLIS
const val TWENTY_FOUR_HOURS_IN_MILLIS = 24 * ONE_HOUR_IN_MILLIS
const val NINETY_NINE_DAYS_IN_MILLIS = 99 * TWENTY_FOUR_HOURS_IN_MILLIS
const val MAX_TIME_IN_WHOLE_MILLISECONDS = 9223372036854775000L
const val SINGLE_MINUTES_SECONDS_FORMAT = "%01d:%02d"
const val DOUBLE_MINUTES_SECONDS_FORMAT = "%02d:%02d"
const val SINGLE_HOURS_MINUTES_SECONDS_FORMAT = "%01d:%02d:%02d"
const val DOUBLE_HOURS_MINUTES_SECONDS_FORMAT = "%02d:%02d:%02d"
const val DAYS_HOURS_MINUTES_SECONDS_FORMAT = "%dd:%02d:%02d:%02d"

// Increment
val INCREMENT_OPTIONS = listOf(.5f, 1f, 2.5f, 5f, 10f)
val REST_TIME_RANGE = 0..6L